### ISSUE TITLE
Compatibility issue with compare_linker-1.3.x

### ISSUE THREAD

**Issue by sanemat** [packsaddle/ruby-compare_linker_wrapper#7]
```
E, [2017-01-17T13:29:02.919418 #7133] ERROR -- CompareLinkerWrapper/1.0.1: Have a question? Please ask us:
E, [2017-01-17T13:29:02.919490 #7133] ERROR -- CompareLinkerWrapper/1.0.1: https://github.com/packsaddle/ruby-compare_linker_wrapper/issues/new
E, [2017-01-17T13:29:02.919513 #7133] ERROR -- CompareLinkerWrapper/1.0.1: options:
E, [2017-01-17T13:29:02.919529 #7133] ERROR -- CompareLinkerWrapper/1.0.1: {"debug"=>false, "verbose"=>false, "base"=>"origin/release", "head"=>"HEAD", "formatter"=>"CompareLinker::Formatter::Markdown"}
ArgumentError: wrong number of arguments (given 1, expected 2)
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker-1.3.4/lib/compare_linker/github_link_finder.rb:9:in `initialize'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:33:in `new'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:33:in `block (2 levels) in link'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:31:in `each'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:31:in `map'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:31:in `block in link'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:25:in `each'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/linker.rb:25:in `link'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/lib/compare_linker_wrapper/cli.rb:36:in `compare'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /path/to/app/vendor/bundle/ruby/2.3.0/gems/compare_linker_wrapper-1.0.1/exe/compare-linker-wrapper:5:in `<top (required)>'
  /path/to/app/vendor/bundle/ruby/2.3.0/bin/compare-linker-wrapper:23:in `load'
  /path/to/app/vendor/bundle/ruby/2.3.0/bin/compare-linker-wrapper:23:in `<top (required)>'
```

**Comment by sanemat** [comment]
Release [v1.0.2](https://github.com/packsaddle/ruby-compare_linker_wrapper/releases/tag/v1.0.2), this uses compare_linker `v1.2.x`.

**Comment by sanemat** [comment]
https://github.com/masutaka/compare_linker/compare/v1.2.1...v1.3.0
